// PetStore  31dea29c0d567213459f86dc9f748282ee11c8c1
// --
// Code generated by webrpc-gen@v0.23.4 with golang generator. DO NOT EDIT.
//
// gospeak .
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/google/uuid"
)

const WebrpcHeader = "Webrpc"

const WebrpcHeaderValue = "webrpc@v0.23.4;gen-golang@v0.18.1;PetStore@v0.0.0-31dea29c0d567213459f86dc9f748282ee11c8c1"

// WebRPC description and code-gen version
func WebRPCVersion() string {
	return "v1"
}

// Schema version of your RIDL schema
func WebRPCSchemaVersion() string {
	return ""
}

// Schema hash generated from your RIDL schema
func WebRPCSchemaHash() string {
	return "31dea29c0d567213459f86dc9f748282ee11c8c1"
}

type WebrpcGenVersions struct {
    WebrpcGenVersion string
    CodeGenName string
    CodeGenVersion string
    SchemaName string
    SchemaVersion string
}

func VersionFromHeader(h http.Header) (*WebrpcGenVersions, error) {
    if h.Get(WebrpcHeader) == "" {
        return nil, fmt.Errorf("header is empty or missing")
    }

    versions, err := parseWebrpcGenVersions(h.Get(WebrpcHeader))
    if err != nil {
        return nil, fmt.Errorf("webrpc header is invalid: %w", err)
    }

    return versions, nil
}

func parseWebrpcGenVersions(header string) (*WebrpcGenVersions, error) {
    versions := strings.Split(header, ";")
    if len(versions) < 3 {
        return nil, fmt.Errorf("expected at least 3 parts while parsing webrpc header: %v", header)
    }

    _, webrpcGenVersion, ok := strings.Cut(versions[0], "@")
    if !ok {
        return nil, fmt.Errorf("webrpc gen version could not be parsed from: %s", versions[0])
    }

    tmplTarget, tmplVersion, ok := strings.Cut(versions[1], "@")
    if !ok {
        return nil, fmt.Errorf("tmplTarget and tmplVersion could not be parsed from: %s", versions[1])
    }

    schemaName, schemaVersion, ok := strings.Cut(versions[2], "@")
    if !ok {
        return nil, fmt.Errorf("schema name and schema version could not be parsed from: %s", versions[2])
    }

    return &WebrpcGenVersions{
        WebrpcGenVersion: webrpcGenVersion,
        CodeGenName: tmplTarget,
        CodeGenVersion: tmplVersion,
        SchemaName: schemaName,
        SchemaVersion: schemaVersion,
    }, nil
}

//
// Common types
//

type Status int

const (
	Status_approved Status = 0
	Status_pending Status = 1
	Status_closed Status = 2
	Status_new Status = 3
)

var Status_name = map[int]string{
	0: "approved",
	1: "pending",
	2: "closed",
	3: "new",
}

var Status_value = map[string]int{
	"approved": 0,
	"pending": 1,
	"closed": 2,
	"new": 3,
}

func (x Status) String() string {
	return Status_name[int(x)]
}

func (x Status) MarshalText() ([]byte, error) {
	return []byte(Status_name[int(x)]), nil
}

func (x *Status) UnmarshalText(b []byte) error {
	*x = Status(Status_value[string(b)])
	return nil
}

func (x *Status) Is(values ...Status) bool {
	if x == nil {
		return false
	}
	for _, v := range values {
		if *x == v {
			return true
		}
	}
	return false
}
type Tag struct {
		ID int64 `json:"ID"`
		Name string `json:"Name"`
}

type Pet struct {
		ID int64 `json:"id,string"`
		UUID uuid.UUID `json:"uuid,string"`
		Name string `json:"name"`
		Available bool `json:"available"`
		PhotoURLs []string `json:"photoUrls"`
		Tags []Tag `json:"tags"`
		CreatedAt time.Time `json:"createdAt"`
		DeletedAt *time.Time `json:"deletedAt"`
		Tag Tag `json:"Tag"`
		TagPtr *Tag `json:"TagPtr"`
		TagsPtr []Tag `json:"TagsPtr"`
		Status Status `json:"status"`
}


var methods = map[string]method{
	"/rpc/PetStore/CreatePet": {
		Name: "CreatePet",
		Service: "PetStore",
		Annotations: map[string]string{},
	},
	"/rpc/PetStore/DeletePet": {
		Name: "DeletePet",
		Service: "PetStore",
		Annotations: map[string]string{},
	},
	"/rpc/PetStore/GetPet": {
		Name: "GetPet",
		Service: "PetStore",
		Annotations: map[string]string{},
	},
	"/rpc/PetStore/ListPets": {
		Name: "ListPets",
		Service: "PetStore",
		Annotations: map[string]string{},
	},
	"/rpc/PetStore/UpdatePet": {
		Name: "UpdatePet",
		Service: "PetStore",
		Annotations: map[string]string{},
	},
}

func WebrpcMethods() map[string]method {
	res := make(map[string]method, len(methods))
	for k, v := range methods {
		res[k] = v
	}

	return res
}

var WebRPCServices = map[string][]string{
	"PetStore": {
		"CreatePet",
		"DeletePet",
		"GetPet",
		"ListPets",
		"UpdatePet",
	},
}

//
// Server types
//

type PetStore interface {
	CreatePet(ctx context.Context, new *Pet) (*Pet, error)
	DeletePet(ctx context.Context, ID int64) error
	GetPet(ctx context.Context, ID int64) (*Pet, error)
	ListPets(ctx context.Context) ([]*Pet, error)
	UpdatePet(ctx context.Context, ID int64, update *Pet) (*Pet, error)
}






//
// Client types
//

type PetStoreClient interface {
	CreatePet(ctx context.Context, new *Pet) (*Pet, error)
	DeletePet(ctx context.Context, ID int64) error
	GetPet(ctx context.Context, ID int64) (*Pet, error)
	ListPets(ctx context.Context) ([]*Pet, error)
	UpdatePet(ctx context.Context, ID int64, update *Pet) (*Pet, error)
}






//
// Client
//

const PetStorePathPrefix = "/rpc/PetStore/"

type petStoreClient struct {
	client HTTPClient
	urls	 [5]string
}

func NewPetStoreClient(addr string, client HTTPClient) PetStoreClient {
	prefix := urlBase(addr) + PetStorePathPrefix
	urls := [5]string{
		prefix + "CreatePet",
		prefix + "DeletePet",
		prefix + "GetPet",
		prefix + "ListPets",
		prefix + "UpdatePet",
	}
	return &petStoreClient{
		client: client,
		urls:	 urls,
	}
}

func (c *petStoreClient) CreatePet(ctx context.Context, new *Pet) (*Pet, error) {
	in := struct {
		Arg0 *Pet `json:"new"`
	}{new}
	out := struct {
		Ret0 *Pet `json:"pet"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[0], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *petStoreClient) DeletePet(ctx context.Context, ID int64) error {
	in := struct {
		Arg0 int64 `json:"ID"`
	}{ID}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[1], in, nil)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return err
}

func (c *petStoreClient) GetPet(ctx context.Context, ID int64) (*Pet, error) {
	in := struct {
		Arg0 int64 `json:"ID"`
	}{ID}
	out := struct {
		Ret0 *Pet `json:"pet"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[2], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *petStoreClient) ListPets(ctx context.Context) ([]*Pet, error) {
	out := struct {
		Ret0 []*Pet `json:"pets"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[3], nil, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

func (c *petStoreClient) UpdatePet(ctx context.Context, ID int64, update *Pet) (*Pet, error) {
	in := struct {
		Arg0 int64 `json:"ID"`
		Arg1 *Pet `json:"update"`
	}{ID, update}
	out := struct {
		Ret0 *Pet `json:"pet"`
	}{}

	resp, err := doHTTPRequest(ctx, c.client, c.urls[4], in, &out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}

	return out.Ret0, err
}

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
		req.Header.Set(WebrpcHeader, WebrpcHeaderValue)
	if headers, ok := HTTPRequestHeaders(ctx); ok {
		for k := range headers {
			for _, v := range headers[k] {
				req.Header.Add(k, v)
			}
		}
	}
	return req, nil
}

// doHTTPRequest is common code to make a request to the remote service.
func doHTTPRequest(ctx context.Context, client HTTPClient, url string, in, out interface{}) (*http.Response, error) {
	reqBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	req, err := newRequest(ctx, url, bytes.NewBuffer(reqBody), "application/json")
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

func WithHTTPRequestHeaders(ctx context.Context, h http.Header) (context.Context, error) {
	if _, ok := h["Accept"]; ok {
		return nil, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return nil, errors.New("provided header cannot set Content-Type")
	}

	copied := make(http.Header, len(h))
	for k, vv := range h {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}

	return context.WithValue(ctx, HTTPClientRequestHeadersCtxKey, copied), nil
}

func HTTPRequestHeaders(ctx context.Context) (http.Header, bool) {
	h, ok := ctx.Value(HTTPClientRequestHeadersCtxKey).(http.Header)
	return h, ok
}

//
// Helpers
//

type method struct  {
	Name string
	Service string
	Annotations map[string]string
}

type contextKey struct {
	name string
}

func (k *contextKey) String() string {
	return "webrpc context value " + k.name
}

var (
	HTTPClientRequestHeadersCtxKey = &contextKey{"HTTPClientRequestHeaders"}
	HTTPRequestCtxKey = &contextKey{"HTTPRequest"}

	ServiceNameCtxKey = &contextKey{"ServiceName"}

	MethodNameCtxKey = &contextKey{"MethodName"}
)

func ServiceNameFromContext(ctx context.Context) string {
	service, _ := ctx.Value(ServiceNameCtxKey).(string)
	return service
}

func MethodNameFromContext(ctx context.Context) string {
	method, _ := ctx.Value(MethodNameCtxKey).(string)
	return method
}

func RequestFromContext(ctx context.Context) *http.Request {
	r, _ := ctx.Value(HTTPRequestCtxKey).(*http.Request)
	return r
}

func MethodCtx(ctx context.Context) (method, bool) {
	req := RequestFromContext(ctx)
	if req == nil {
		return method{}, false
	}

	m, ok := methods[req.URL.Path]
	if !ok {
		return method{}, false
	}

	return m, true
}



//
// Errors
//

type WebRPCError struct {
	Name       string `json:"error"`
	Code       int    `json:"code"`
	Message    string `json:"msg"`
	Cause      string `json:"cause,omitempty"`
	HTTPStatus int    `json:"status"`
	cause      error
}

var _ error = WebRPCError{}

func (e WebRPCError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s %d: %s: %v", e.Name, e.Code, e.Message, e.cause)
	}
	return fmt.Sprintf("%s %d: %s", e.Name, e.Code, e.Message)
}

func (e WebRPCError) Is(target error) bool {
	if target == nil {
		return false
	}
	if rpcErr, ok := target.(WebRPCError); ok {
		return rpcErr.Code == e.Code
	}
	return errors.Is(e.cause, target)
}

func (e WebRPCError) Unwrap() error {
	return e.cause
}

func (e WebRPCError) WithCause(cause error) WebRPCError {
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

func (e WebRPCError) WithCausef(format string, args ...interface{}) WebRPCError {
	cause := fmt.Errorf(format, args...)
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

// Deprecated: Use .WithCause() method on WebRPCError.
func ErrorWithCause(rpcErr WebRPCError, cause error) WebRPCError {
	return rpcErr.WithCause(cause)
}

// Webrpc errors
var (
	ErrWebrpcEndpoint = WebRPCError{Code: 0, Name: "WebrpcEndpoint", Message: "endpoint error", HTTPStatus: 400}
	ErrWebrpcRequestFailed = WebRPCError{Code: -1, Name: "WebrpcRequestFailed", Message: "request failed", HTTPStatus: 400}
	ErrWebrpcBadRoute = WebRPCError{Code: -2, Name: "WebrpcBadRoute", Message: "bad route", HTTPStatus: 404}
	ErrWebrpcBadMethod = WebRPCError{Code: -3, Name: "WebrpcBadMethod", Message: "bad method", HTTPStatus: 405}
	ErrWebrpcBadRequest = WebRPCError{Code: -4, Name: "WebrpcBadRequest", Message: "bad request", HTTPStatus: 400}
	ErrWebrpcBadResponse = WebRPCError{Code: -5, Name: "WebrpcBadResponse", Message: "bad response", HTTPStatus: 500}
	ErrWebrpcServerPanic = WebRPCError{Code: -6, Name: "WebrpcServerPanic", Message: "server panic", HTTPStatus: 500}
	ErrWebrpcInternalError = WebRPCError{Code: -7, Name: "WebrpcInternalError", Message: "internal error", HTTPStatus: 500}
	ErrWebrpcClientDisconnected = WebRPCError{Code: -8, Name: "WebrpcClientDisconnected", Message: "client disconnected", HTTPStatus: 400}
	ErrWebrpcStreamLost = WebRPCError{Code: -9, Name: "WebrpcStreamLost", Message: "stream lost", HTTPStatus: 400}
	ErrWebrpcStreamFinished = WebRPCError{Code: -10, Name: "WebrpcStreamFinished", Message: "stream finished", HTTPStatus: 200}
)